DefaultContentLanguage = "en"
languageCode = "en"
title = "kaowebdev"
[languages.en]
LanguageName = "en"
languageCode = "en"
weight = 1
[[languages.en.menu.nav]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[languages.en.menu.nav]]
identifier = "about"
name = "About"
url = "/about"
weight = 2
[[languages.en.menu.nav]]
identifier = "projects"
name = "Projects"
url = "/solution"
weight = 3
[[languages.en.menu.nav]]
identifier = "contacts"
name = "Contact"
url = "/contact"
weight = 4
[languages.ru]
LanguageName = "ru"
languageCode = "ru"
weight = 2
[[languages.ru.menu.nav]]
identifier = "home"
name = "Главная"
url = "/"
weight = 1
[[languages.ru.menu.nav]]
identifier = "about"
name = "О мне"
url = "/about"
weight = 2
[[languages.ru.menu.nav]]
identifier = "projects"
name = "Проекты"
url = "/solution"
weight = 3
[[languages.ru.menu.nav]]
identifier = "contacts"
name = "Контакты"
url = "/contact"
weight = 4
[params.mail]
mail1 = "kaowebdev@gmail.com"
mail2 = "assdwqe@gmail.com"
[params.meta]
description = "This presonal site of junior frontend developer"
[taxonomies]
category = "categories"
tag = "tags"
