# baseURL = "http://kaowebdesign.github.io/"
languageCode = "en"
title = "kaowebdev"
DefaultContentLanguage = "en"

[taxonomies]
  tag = "tags"
  category = "categories"

[params.mail]
    mail1 = "kaowebdev@gmail.com"
    mail2 = "assdwqe@gmail.com"

[params.meta]
    # Sets the meta tag description
    description  = "This presonal site of junior frontend developer"

[languages]
   
    [languages.ru]
        languageCode = "ru"
        LanguageName = "ru"
        weight = 2
        
    [languages.en]
        languageCode = "en"
        LanguageName = "en"
        weight = 1
        
# russian menu
#     [[languages.ru.menu.nav]]
#         identifier = "home"
#         name= "Главная"
#         url = "/"
#         weight = 1
#     [[languages.ru.menu.nav]]
#         identifier = "about"
#         name= "О мне"
#         url = "/about"
#         weight = 2
#     [[languages.ru.menu.nav]]
#         identifier = "projects"
#         name= "Проекты"
#         url = "/solution"
#         weight = 3
#     [[languages.ru.menu.nav]]
#         identifier = "contacts"
#         name= "Контакты"
#         url = "/contact"
#         weight = 4
# # english menu
#     [[languages.en.menu.nav]]
#         identifier = "home"
#         name= "Home"
#         url = "/"
#         weight = 1
#     [[languages.en.menu.nav]]
#         identifier = "about"
#         name= "About"
#         url = "/about"
#         weight = 2
#     [[languages.en.menu.nav]]
#         identifier = "projects"
#         name= "Projects"
#         url = "/solution"
#         weight = 3
#     [[languages.en.menu.nav]]
#         identifier = "contacts"
#         name= "Contact"
#         url = "/contact"
#         weight = 4
        


